In [1]:
# Import required libraries and dependencies
import pandas as pd
import hvplot.pandas
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [2]:
# Load the data into a Pandas DataFrame
df_market_data = pd.read_csv(
    "Resources/crypto_market_data.csv",
    index_col="coin_id")

# Display sample data
display(df_market_data.head(10))
df_market_data.info()
df_market_data.columns

price_change_percentage_24h  price_change_percentage_7d  \
coin_id                                                                    
bitcoin                              1.08388                     7.60278   
ethereum                             0.22392                    10.38134   
tether                              -0.21173                     0.04935   
ripple                              -0.37819                    -0.60926   
bitcoin-cash                         2.90585                    17.09717   
binancecoin                          2.10423                    12.85511   
chainlink                           -0.23935                    20.69459   
cardano                              0.00322                    13.99302   
litecoin                            -0.06341                     6.60221   
bitcoin-cash-sv                      0.92530                     3.29641   

                 price_change_percentage_14d  price_change_percentage_30d  \
coin_id                                                                     
bitcoin                              6.57509                      7.67258   
ethereum                             4.80849                      0.13169   
tether                               0.00640                     -0.04237   
ripple                               2.24984                      0.23455   
bitcoin-cash                        14.75334                     15.74903   
binancecoin                          6.80688                      0.05865   
chainlink                            9.30098                    -11.21747   
cardano                              5.55476                     10.10553   
litecoin                             7.28931                      1.21662   
bitcoin-cash-sv                     -1.86656                      2.88926   

                 price_change_percentage_60d  price_change_percentage_200d  \
coin_id                                                                      
bitcoin                             -3.25185                      83.51840   
ethereum                           -12.88890                     186.77418   
tether                               0.28037                      -0.00542   
ripple                             -17.55245                      39.53888   
bitcoin-cash                       -13.71793                      21.66042   
binancecoin                         36.33486                     155.61937   
chainlink                          -43.69522                     403.22917   
cardano                            -22.84776                     264.51418   
litecoin                           -17.23960                      27.49919   
bitcoin-cash-sv                    -24.87434                       7.42562   

                 price_change_percentage_1y  
coin_id                                      
bitcoin                            37.51761  
ethereum                          101.96023  
tether                              0.01954  
ripple                            -16.60193  
bitcoin-cash                       14.49384  
binancecoin                        69.69195  
chainlink                         325.13186  
cardano                           156.09756  
litecoin                          -12.66408  
bitcoin-cash-sv                    93.73082

<class 'pandas.core.frame.DataFrame'>
Index: 41 entries, bitcoin to digibyte
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   price_change_percentage_24h   41 non-null     float64
 1   price_change_percentage_7d    41 non-null     float64
 2   price_change_percentage_14d   41 non-null     float64
 3   price_change_percentage_30d   41 non-null     float64
 4   price_change_percentage_60d   41 non-null     float64
 5   price_change_percentage_200d  41 non-null     float64
 6   price_change_percentage_1y    41 non-null     float64
dtypes: float64(7)
memory usage: 2.6+ KB


Index(['price_change_percentage_24h', 'price_change_percentage_7d',
       'price_change_percentage_14d', 'price_change_percentage_30d',
       'price_change_percentage_60d', 'price_change_percentage_200d',
       'price_change_percentage_1y'],
      dtype='object')

In [3]:
# Generate summary statistics
df_market_data.describe()

price_change_percentage_24h  price_change_percentage_7d  \
count                    41.000000                   41.000000   
mean                     -0.269686                    4.497147   
std                       2.694793                    6.375218   
min                     -13.527860                   -6.094560   
25%                      -0.608970                    0.047260   
50%                      -0.063410                    3.296410   
75%                       0.612090                    7.602780   
max                       4.840330                   20.694590   

       price_change_percentage_14d  price_change_percentage_30d  \
count                    41.000000                    41.000000   
mean                      0.185787                     1.545693   
std                       8.376939                    26.344218   
min                     -18.158900                   -34.705480   
25%                      -5.026620                   -10.438470   
50%                       0.109740                    -0.042370   
75%                       5.510740                     4.578130   
max                      24.239190                   140.795700   

       price_change_percentage_60d  price_change_percentage_200d  \
count                    41.000000                     41.000000   
mean                     -0.094119                    236.537432   
std                      47.365803                    435.225304   
min                     -44.822480                     -0.392100   
25%                     -25.907990                     21.660420   
50%                      -7.544550                     83.905200   
75%                       0.657260                    216.177610   
max                     223.064370                   2227.927820   

       price_change_percentage_1y  
count                   41.000000  
mean                   347.667956  
std                   1247.842884  
min                    -17.567530  
25%                      0.406170  
50%                     69.691950  
75%                    168.372510  
max                   7852.089700

In [4]:
# Plot your data to see what's in your DataFrame
df_market_data.hvplot.line(
    width=800,
    height=400,
    rot=90
)

:NdOverlay   [Variable]
   :Curve   [coin_id]   (value)

---

### Prepare the Data

In [7]:
# Use the `StandardScaler()` module from scikit-learn to normalize the data from the CSV file
market_data_scaled = StandardScaler().fit_transform(df_market_data)

# Create a DataFrame with the scaled data
df_market_data_scaled = pd.DataFrame(market_data_scaled, columns= ['price_change_percentage_24h', 
                                                                   'price_change_percentage_7d',
                                                                   'price_change_percentage_14d', 
                                                                   'price_change_percentage_30d',
                                                                   'price_change_percentage_60d', 
                                                                   'price_change_percentage_200d',
                                                                   'price_change_percentage_1y']
                                                                   )


# Copy the crypto names from the original data
df_market_data_scaled['coinid'] = df_market_data.index

# Set the coinid column as index
df_market_data_scaled = df_market_data_scaled.set_index('coinid')

# Display sample data
display(df_market_data_scaled.head())

df_market_data_scaled.hvplot.line(
    width=800,
    height=400,
    rot=90
)

price_change_percentage_24h  price_change_percentage_7d  \
coinid                                                                  
bitcoin                          0.508529                    0.493193   
ethereum                         0.185446                    0.934445   
tether                           0.021774                   -0.706337   
ripple                          -0.040764                   -0.810928   
bitcoin-cash                     1.193036                    2.000959   

              price_change_percentage_14d  price_change_percentage_30d  \
coinid                                                                   
bitcoin                          0.772200                     0.235460   
ethereum                         0.558692                    -0.054341   
tether                          -0.021680                    -0.061030   
ripple                           0.249458                    -0.050388   
bitcoin-cash                     1.760610                     0.545842   

              price_change_percentage_60d  price_change_percentage_200d  \
coinid                                                                    
bitcoin                         -0.067495                     -0.355953   
ethereum                        -0.273483                     -0.115759   
tether                           0.008005                     -0.550247   
ripple                          -0.373164                     -0.458259   
bitcoin-cash                    -0.291203                     -0.499848   

              price_change_percentage_1y  
coinid                                    
bitcoin                        -0.251637  
ethereum                       -0.199352  
tether                         -0.282061  
ripple                         -0.295546  
bitcoin-cash                   -0.270317

:NdOverlay   [Variable]
   :Curve   [coinid]   (value)

---

### Find the Best Value for k Using the Original Data.

In [8]:
# Create a list with the number of k-values from 1 to 11
k = list(range(1,11))

# Create an empty list to store the inertia values
inertia = []

# Create a for loop to compute the inertia with each possible value of k
# Inside the loop:
# 1. Create a KMeans model using the loop counter for the n_clusters
# 2. Fit the model to the data using `df_market_data_scaled`
# 3. Append the model.inertia_ to the inertia list
for i in k:
    k_model = KMeans(n_clusters=i, random_state=2)
    k_model.fit(df_market_data_scaled)
    inertia.append(k_model.inertia_)

# Create a dictionary with the data to plot the Elbow curve
elbow_data = {"k": k,
              "inertia" : inertia}

# Create a DataFrame with the data to plot the Elbow curve
df_elbow = pd.DataFrame(elbow_data)
df_elbow.head()

/Users/michaelnaffziger/opt/anaconda3/envs/dev/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/Users/michaelnaffziger/opt/anaconda3/envs/dev/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/Users/michaelnaffziger/opt/anaconda3/envs/dev/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/Users/michaelnaffziger/opt/anaconda3/envs/dev/lib/python3.10/site-packages/

k     inertia
0  1  287.000000
1  2  198.571818
2  3  123.190482
3  4   79.022435
4  5   63.858668

In [9]:
# Plot a line chart with all the inertia values computed with 
# the different values of k to visually identify the optimal value for k.
plot_elbow_orig = df_elbow.hvplot.line(
    x = "k",
    y = "inertia",
    title = "Elbow Curve of Original Fitted Data",
    xticks = k
)

plot_elbow_orig

:Curve   [k]   (inertia)

#### Answer the following question: 

**Question:** What is the best value for `k`?

**Answer:** At k = 4 the difference in inertia starts to level off.  I would start at k = 4 and evaluate the predicted clusters.

---

### Cluster Cryptocurrencies with K-means Using the Original Data

In [10]:
# Initialize the K-Means model using the best value for k
model_k4 = KMeans(n_clusters= 4, random_state= 1)

# Fit the K-Means model using the scaled data
model_k4.fit(df_market_data_scaled)

# Predict the clusters to group the cryptocurrencies using the scaled data
k_4 = model_k4.predict(df_market_data_scaled)

# Print the resulting array of cluster values.
k_4[:20]

/Users/michaelnaffziger/opt/anaconda3/envs/dev/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


array([2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 0],
      dtype=int32)

In [11]:
# Create a copy of the DataFrame
df_market_data_pred_k4 = df_market_data_scaled.copy()

# Add a new column to the DataFrame with the predicted clusters
df_market_data_pred_k4['pred k= 4'] = k_4

# Display sample data
df_market_data_pred_k4.head()

price_change_percentage_24h  price_change_percentage_7d  \
coinid                                                                  
bitcoin                          0.508529                    0.493193   
ethereum                         0.185446                    0.934445   
tether                           0.021774                   -0.706337   
ripple                          -0.040764                   -0.810928   
bitcoin-cash                     1.193036                    2.000959   

              price_change_percentage_14d  price_change_percentage_30d  \
coinid                                                                   
bitcoin                          0.772200                     0.235460   
ethereum                         0.558692                    -0.054341   
tether                          -0.021680                    -0.061030   
ripple                           0.249458                    -0.050388   
bitcoin-cash                     1.760610                     0.545842   

              price_change_percentage_60d  price_change_percentage_200d  \
coinid                                                                    
bitcoin                         -0.067495                     -0.355953   
ethereum                        -0.273483                     -0.115759   
tether                           0.008005                     -0.550247   
ripple                          -0.373164                     -0.458259   
bitcoin-cash                    -0.291203                     -0.499848   

              price_change_percentage_1y  pred k= 4  
coinid                                               
bitcoin                        -0.251637          2  
ethereum                       -0.199352          2  
tether                         -0.282061          0  
ripple                         -0.295546          0  
bitcoin-cash                   -0.270317          2

In [12]:
# Create a scatter plot using hvPlot by setting 
# `x="price_change_percentage_24h"` and `y="price_change_percentage_7d"`. 
# Color the graph points with the labels found using K-Means and 
# add the crypto name in the `hover_cols` parameter to identify 
# the cryptocurrency represented by each data point.

plot_orig_k_4 = df_market_data_pred_k4.hvplot.scatter(
    x = "price_change_percentage_24h",
    y = "price_change_percentage_7d",
    by= "pred k= 4",
    title= "Original Data Cluster Predictions, k = 4",
    hover_cols = 'coinid' # eventhough 'coinid' is dba the datafram index, since it is defined as 'coinid' I can just call it directly instead of 'index'
)

plot_orig_k_4


:NdOverlay   [pred k= 4]
   :Scatter   [price_change_percentage_24h]   (price_change_percentage_7d,coinid)

---

### Optimize Clusters with Principal Component Analysis.

In [13]:
# Create a PCA model instance and set `n_components=3`.
pca = PCA(n_components=3)

# Use the PCA model with `fit_transform` to reduce to 
# three principal components.
market_data_pca = pca.fit_transform(df_market_data_scaled)
# View the first five rows of the DataFrame. 
market_data_pca[:5]

array([[-0.60066733,  0.84276006,  0.46159457],
       [-0.45826071,  0.45846566,  0.95287678],
       [-0.43306981, -0.16812638, -0.64175193],
       [-0.47183495, -0.22266008, -0.47905316],
       [-1.15779997,  2.04120919,  1.85971527]])

In [14]:
# Retrieve the explained variance to determine how much information 
# can be attributed to each principal component.
pca.explained_variance_ratio_

array([0.3719856 , 0.34700813, 0.17603793])

#### Answer the following question: 

**Question:** What is the total explained variance of the three principal components?

**Answer:** It explains the percentage of the data that is represented by the PCA model.  When the dimentions of this dataset were reduced, the model accounted for ~90% of the features from the original, scaled dataset.

In [15]:
# Create a new DataFrame with the PCA data.
df_market_data_pca = pd.DataFrame(market_data_pca, columns=['PCA_1', 'PCA_2', 'PCA_3'])

# # Copy the crypto names from the original data
df_market_data_pca['coinid'] = df_market_data.index

# # Set the coinid column as index
df_market_data_pca = df_market_data_pca.set_index('coinid')

# Display sample data
df_market_data_pca.head()


PCA_1     PCA_2     PCA_3
coinid                                    
bitcoin      -0.600667  0.842760  0.461595
ethereum     -0.458261  0.458466  0.952877
tether       -0.433070 -0.168126 -0.641752
ripple       -0.471835 -0.222660 -0.479053
bitcoin-cash -1.157800  2.041209  1.859715

---

### Find the Best Value for k Using the PCA Data

In [16]:
# Create a list with the number of k-values from 1 to 11
k_pca = list(range(1,11))

# Create an empty list to store the inertia values
inertia_pca = []

# Create a for loop to compute the inertia with each possible value of k
# Inside the loop:
# 1. Create a KMeans model using the loop counter for the n_clusters
# 2. Fit the model to the data using `df_market_data_pca`
# 3. Append the model.inertia_ to the inertia list
for i in k_pca:
    k_model = KMeans(n_clusters=i, random_state=2)
    k_model.fit(df_market_data_pca)
    inertia_pca.append(k_model.inertia_)

# Create a dictionary with the data to plot the Elbow curve
elbow_data_pca = {
    'k_pca' : k_pca,
    'inertia_pca' : inertia_pca
}
# Create a DataFrame with the data to plot the Elbow curve
df_elbow_pca = pd.DataFrame(elbow_data_pca)
# df_elbow_pca.head(10)

# Plot a line chart with all the inertia values computed with 
# the different values of k to visually identify the optimal value for k.
plot_elbow_pca_3 = df_elbow_pca.hvplot.line(
    x = 'k_pca',
    y = 'inertia_pca',
    title = 'Elbow Curve of PCA Data, Components = 3',
    xticks = k_pca
)

plot_elbow_pca_3

/Users/michaelnaffziger/opt/anaconda3/envs/dev/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/Users/michaelnaffziger/opt/anaconda3/envs/dev/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/Users/michaelnaffziger/opt/anaconda3/envs/dev/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/Users/michaelnaffziger/opt/anaconda3/envs/dev/lib/python3.10/site-packages/

:Curve   [k_pca]   (inertia_pca)

#### Answer the following questions: 

* **Question:** What is the best value for `k` when using the PCA data?

  * **Answer:** From the PCA elbow plot, k= 4 still looks like the best value


* **Question:** Does it differ from the best k value found using the original data?

  * **Answer:** No

### Cluster Cryptocurrencies with K-means Using the PCA Data

In [17]:
# Initialize the K-Means model using the best value for k
model_pca = KMeans(n_clusters=4)

# Fit the K-Means model using the PCA data
model_pca.fit(df_market_data_pca)

# Predict the clusters to group the cryptocurrencies using the PCA data
market_data_pca_clusters = model_pca.predict(df_market_data_pca)

# Print the resulting array of cluster values.
print(market_data_pca_clusters)

[1 1 0 0 1 1 1 1 1 0 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 2 1 0 0 3
 0 0 0 0]


/Users/michaelnaffziger/opt/anaconda3/envs/dev/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


In [18]:
# Create a copy of the DataFrame with the PCA data
df_market_data_pca_pred = df_market_data_pca.copy()

# Add a new column to the DataFrame with the predicted clusters
df_market_data_pca_pred['pred_clusters'] = market_data_pca_clusters

# Display sample data
df_market_data_pca_pred.head(10)

PCA_1     PCA_2     PCA_3  pred_clusters
coinid                                                      
bitcoin         -0.600667  0.842760  0.461595              1
ethereum        -0.458261  0.458466  0.952877              1
tether          -0.433070 -0.168126 -0.641752              0
ripple          -0.471835 -0.222660 -0.479053              0
bitcoin-cash    -1.157800  2.041209  1.859715              1
binancecoin     -0.516534  1.388377  0.804071              1
chainlink       -0.450711  0.517699  2.846143              1
cardano         -0.345600  0.729439  1.478013              1
litecoin        -0.649468  0.432165  0.600303              1
bitcoin-cash-sv -0.759014 -0.201200 -0.217653              0

In [23]:
# Create a scatter plot using hvPlot by setting 
# `x="PC1"` and `y="PC2"`. 
# Color the graph points with the labels found using K-Means and 
# add the crypto name in the `hover_cols` parameter to identify 
# the cryptocurrency represented by each data point.

plot_pca_3_k_4_PCA12 = df_market_data_pca_pred.hvplot.scatter(
    x = 'PCA_1',
    y = 'PCA_2',
    by = 'pred_clusters',
    title = "PCA Fitted Model of Original Data. Compenents = 3, k = 4",
    hover_cols = 'coinid'
    )
plot_pca_3_k_4_PCA13 = df_market_data_pca_pred.hvplot.scatter(
    x = 'PCA_1',
    y = 'PCA_3',
    by = 'pred_clusters',
    title = "PCA Fitted Model of Original Data. Compenents = 3, k = 4",
    hover_cols = 'coinid'
    )
plot_pca_3_k_4_PCA23 = df_market_data_pca_pred.hvplot.scatter(
    x = 'PCA_2',
    y = 'PCA_3',
    by = 'pred_clusters',
    title = "PCA Fitted Model of Original Data. Compenents = 3, k = 4",
    hover_cols = 'coinid'
    )
(plot_pca_3_k_4_PCA12 + plot_pca_3_k_4_PCA13 + plot_pca_3_k_4_PCA23).cols(2) 

:Layout
   .NdOverlay.I   :NdOverlay   [pred_clusters]
      :Scatter   [PCA_1]   (PCA_2,coinid)
   .NdOverlay.II  :NdOverlay   [pred_clusters]
      :Scatter   [PCA_1]   (PCA_3,coinid)
   .NdOverlay.III :NdOverlay   [pred_clusters]
      :Scatter   [PCA_2]   (PCA_3,coinid)

### Visualize and Compare the Results

In this section, you will visually analyze the cluster analysis results by contrasting the outcome with and without using the optimization techniques.

In [24]:
# Composite plot to contrast the Elbow curves

plot_elbow_orig + plot_elbow_pca_3

:Layout
   .Curve.I  :Curve   [k]   (inertia)
   .Curve.II :Curve   [k_pca]   (inertia_pca)

In [26]:
# Composite plot to contrast the clusters
plot_orig_k_4 + plot_pca_3_k_4_PCA12

:Layout
   .NdOverlay.I  :NdOverlay   [pred k= 4]
      :Scatter   [price_change_percentage_24h]   (price_change_percentage_7d,coinid)
   .NdOverlay.II :NdOverlay   [pred_clusters]
      :Scatter   [PCA_1]   (PCA_2,coinid)

#### Answer the following question: 

  * **Question:** After visually analyzing the cluster analysis results, what is the impact of using fewer features to cluster the data using K-Means?

  * **Answer:**  With this dataset, the PCA model dropped ~10% of the information that did not fit the model.  This resulted in a tighter clustering of the data to visualize the clustering better.  In both plots, coins ethlend and celsius-degree-token are both single members of different groups.  From the original scaled data plot, only coin ethlend is visualized easily as a separate cluster.  Coin celsius-degree-token is burried within another cluster and would be missed if it was not color coded.  The PCA model effectively separated both the ethlend and celsius-degree-token from the other two clusters.  The PCA model also appears to have provided a cleaner, more distinct boundry between clusters 0 and 1 (blue and red respectfully) than the original data's cluster plot

In [29]:
#-----
# Addition analysis of which feature is strongly related to  / corresponds with each PCA component
# Determin which of the features correspond to each PCA component and visualize the weights assigned from the model
market_data_pca_components = pca.components_
df_market_data_pca_components = pd.DataFrame(market_data_pca_components, columns=['price_change_percentage_24h', 'price_change_percentage_7d',
       'price_change_percentage_14d', 'price_change_percentage_30d','price_change_percentage_60d', 'price_change_percentage_200d','price_change_percentage_1y'])
model_components = ['PCA_1', 'PCA_2', 'PCA_3']
df_market_data_pca_components['components'] = model_components
df_market_data_pca_components = df_market_data_pca_components.set_index('components')
display(df_market_data_pca_components.head())

# Convert the loadings DataFrame into a long format for easier plotting
df_weights = df_market_data_pca_components.reset_index().melt(id_vars='components')

# Rename the columns for clarity
df_weights.columns = ['pca_component', 'feature', 'weight']
df_weights['weight'] = df_weights['weight'].abs()

width = 800
height = 600
# Create the hvplot line plot
plot_pca_weights_bar = df_weights.hvplot.bar(
    x = 'feature',y='weight',
    by = 'pca_component', stacked = True,
    xlabel='PCA Component',ylabel='Absolute Value of Feature Weight',
    title= 'Feature Weight on Each PCA Component',
    rot = 45,
    height = height,
    width = width
)
plot_pca_weights_bar

price_change_percentage_24h  price_change_percentage_7d  \
components                                                            
PCA_1                         -0.416728                   -0.102432   
PCA_2                          0.358162                    0.227432   
PCA_3                         -0.218795                    0.787670   

            price_change_percentage_14d  price_change_percentage_30d  \
components                                                             
PCA_1                         -0.009162                     0.191523   
PCA_2                          0.540415                     0.562182   
PCA_3                          0.349534                    -0.181744   

            price_change_percentage_60d  price_change_percentage_200d  \
components                                                              
PCA_1                          0.320365                      0.594468   
PCA_2                          0.434040                      0.027735   
PCA_3                         -0.361377                      0.039733   

            price_change_percentage_1y  
components                              
PCA_1                         0.568379  
PCA_2                        -0.150789  
PCA_3                         0.210541

:Bars   [feature,pca_component]   (weight)

#### PCA Component and Feature Relationships

All three compenents weighted the daily price change almost equally, with a higher absolute value of weight assigned to PCA_1 (0.417) and PCA_2 (0.358)

* **PCA_1:** Represents the variances related to more of the long term prices changes (>200 days).  This component could be seen as an annual price performance

* **PCA_2:** Represents the variances related to mid term price changes between 14 - 60 days.  This component could be seen as a quarterly price preformance

* **PCA_3:** Represents the variances related to shorter term price changes between 7 days.  This component could be seen as a weekly price preformance